### ISSUE TITLE
Fail in Ubuntu

### ISSUE THREAD

**Issue by johnlarfour** [syvaidya/openstego#28]
After downloading openstego_0.7.3-1_amd64.deb and install it, when i try to open it i get this error:
<pre>
<code>
Exception in thread "main" java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
	at java.desktop/java.awt.Toolkit.newAWTError(Toolkit.java:472)
	at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:488)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1608)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.desktop/java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:532)
	at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:613)
	at java.desktop/javax.swing.UIManager.getSystemLookAndFeelClassName(UIManager.java:660)
	at com.openstego.desktop.OpenStego.main(OpenStego.java:433)
Caused by: java.lang.ClassNotFoundException: org.GNOME.Accessibility.AtkWrapper
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:485)
	... 13 more

</code>
</pre>
I tried the command `dos2unix` in path `/usr/share/openstego/openstego`
But I get the same result

**Comment by johnlarfour** [comment]
I solved with by editing the accessibility.properties file for openjdk and comment this line:
`assistive_technologies=org.GNOME.Accessibility.AtkWrapper` 
But I'm not an expert with Java and i don't know if it's a safe method to solve this issue...
If it's ok, you can close this issue.
Thank you

**Comment by syvaidya** [comment]
I think that change should be fine. Seems that many people face this with Ubuntu java.
