### ISSUE TITLE
Unable to see/find extracted txt file.

### ISSUE THREAD

**Issue by dkhill** [syvaidya/openstego#7]
I hid some data within a picture.  Operation showed that it exceeded, but when I went to extract the data message says successful but had a (null) in the successful message.  And there was no extractd file.
Says:  Message successfully extracted from the cover file: null
Environment:  Windows 10
Password Used:  Yes.

Java Errors Found in Window:
java.util.concurrent.ExecutionException: net.sourceforge.openstego.OpenStegoException: java.io.FileNotFoundException: C:\Temp\Extracted.txt\Boot Time Errors.txt **(The system cannot find the path specified)**
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at javax.swing.SwingWorker.get(Unknown Source)
        at net.sourceforge.openstego.ui.OpenStegoUI$2.done(OpenStegoUI.java:395)
        at javax.swing.SwingWorker$5.run(Unknown Source)
        at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
        at sun.swing.AccumulativeRunnable.run(Unknown Source)
        at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
        at javax.swing.Timer.fireActionPerformed(Unknown Source)
        at javax.swing.Timer$DoPostEvent.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: net.sourceforge.openstego.OpenStegoException: java.io.FileNotFoundException: C:\Temp\Extracted.txt\Boot Time Errors.txt (The system cannot find the path specified)
        at net.sourceforge.openstego.util.CommonUtil.writeFile(CommonUtil.java:138)
        at net.sourceforge.openstego.util.CommonUtil.writeFile(CommonUtil.java:108)
        at net.sourceforge.openstego.ui.OpenStegoUI$2.doInBackground(OpenStegoUI.java:379)
        at javax.swing.SwingWorker$1.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at javax.swing.SwingWorker.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: C:\Temp\Extracted.txt\Boot Time Errors.txt (The system cannot find the path specified)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at net.sourceforge.openstego.util.CommonUtil.writeFile(CommonUtil.java:131)
        ... 8 more

**Comment by syvaidya** [comment]
Can you please try with file having no spaces in its name? Current one has spaces in it "Boot Time Errors.txt". Let me know if that works - it would mean that there is some bug in code which is not able to handle spaces in file name.

**Comment by syvaidya** [comment]
Closing, as there is no update for long.
